-- recorder.lua — recordable/replayable dummy input slots.
--
-- 4 slots of per-frame normalized bitmasks (facing-relative: back/fwd, so a recording
-- mirrors correctly when sides swap). Recording flow (pad or keys):
--   * key 'R' (or the menu/pad flow) arms recording into the current slot and turns on
--     pad-swap: your pad now drives the DUMMY. Recording starts on the first non-neutral
--     input, ends on 'R' again (trailing neutral trimmed).
--   * key 'T' plays the current slot once; the trigger mode ('U' key / menu) can instead
--     fire it automatically: manual / loop / on_wakeup / on_blockstun_end / on_hitstun_end
--     / random (random picks any non-empty slot each time) / gc.
--   * 'gc' = GUARD-CANCEL TRAINER: the slot fires on blockstun ENTRY, so a recorded
--     special motion completes inside the stun and cancels it (record the dummy character's
--     special once, set guard=all + trigger=gc, then run your blockstrings — the dummy
--     GCs through them). M.gcChance (menu "gc chance") makes it probabilistic so you can
--     practice hit-confirming vs random GCs.
--   * reversal timing needs no knob: playback fires on the first free frame's input
--     poll, and the engine's press-latch makes that frame-perfect for move starts
--     (an earlier documented reversal_lead cfg was never read and is gone — #18).
-- Persistence: traces/training_slots.lua (auto-saved on record end, auto-loaded at boot).
local M = {}

function M.init(ctx)
  local C = ctx.C
  local input = ctx.mod.input
  local gs = ctx.mod.gamestate
  local SLOTS_FILE = ctx.ROOT .. "../traces/training_slots.lua"

  M.slots = { {}, {}, {}, {} }          -- [n] = array of masks
  M.cur = 1
  M.trigger = "manual"                  -- manual|loop|wakeup|blockstun|hitstun|random|gc
  M.gcChance = 100                      -- % chance the gc trigger fires per blockstun entry
  M.state = "idle"                      -- idle|armed|recording|playing
  M.playPos = 0
  M.playSlot = 1
  local dummyPort = 2                   -- player index being driven (P2)

  local TRIGGERS = { "manual", "loop", "wakeup", "blockstun", "hitstun", "random", "gc" }

  -- ---- persistence ----
  local function saveSlots()
    if M.slotsReadOnly then return end   -- issue #31: never overwrite a corrupt slots file
    local ok = pcall(function()
      local f = assert(io.open(SLOTS_FILE, "w"))
      f:write("-- generated by tools/training/recorder.lua\nreturn {\n")
      for n = 1, 4 do
        f:write("  { " .. table.concat(M.slots[n], ",") .. " },\n")
      end
      f:write("}\n")
      f:close()
    end)
    if not ok and not ctx.headless then
      emu.displayMessage("training", "slot save failed (io access off?)")
    end
  end
  local function loadSlots()
    local f = io.open(SLOTS_FILE, "r")
    if not f then return end               -- absent: fresh slots, saving is fine
    f:close()
    local ok, data = pcall(dofile, SLOTS_FILE)
    if ok and type(data) == "table" then
      for n = 1, 4 do M.slots[n] = data[n] or {} end
    else
      -- issue #31: corrupt file — do NOT let a later save wipe the on-disk slots
      M.slotsReadOnly = true
      print("training: slots file unreadable — recording enabled but persistence OFF for this session")
    end
  end
  loadSlots()

  -- ---- state control ----
  local function beginRecord()
    M.state = "armed"
    M.slots[M.cur] = {}
    ctx.ui.padSwap = true
    if not ctx.headless then
      emu.displayMessage("training", "REC slot " .. M.cur .. ": armed (first input starts)")
    end
  end
  local function endRecord()
    -- trim trailing neutral
    local s = M.slots[M.cur]
    while #s > 0 and s[#s] == 0 do table.remove(s) end
    M.state = "idle"
    ctx.ui.padSwap = false
    saveSlots()
    if not ctx.headless then
      emu.displayMessage("training", "REC slot " .. M.cur .. ": " .. #s .. " frames")
    end
  end
  local function startPlay(slot)
    slot = slot or M.cur
    if M.trigger == "random" then
      local nonEmpty = {}
      for n = 1, 4 do if #M.slots[n] > 0 then nonEmpty[#nonEmpty + 1] = n end end
      if #nonEmpty == 0 then return end
      slot = nonEmpty[math.random(#nonEmpty)]   -- issue #17: was frame-modulo = deterministic
    end
    if #M.slots[slot] == 0 then return end
    M.state = "playing"; M.playSlot = slot; M.playPos = 1
  end
  M.startPlay = startPlay

  ctx.actions.record = function()
    if M.state == "recording" or M.state == "armed" then endRecord() else beginRecord() end
  end
  ctx.actions.play = function()
    if M.state == "playing" then M.state = "idle" else startPlay() end
  end
  ctx.actions.slot = function()
    M.cur = (M.cur % 4) + 1
    if not ctx.headless then emu.displayMessage("training",
      "slot " .. M.cur .. " (" .. #M.slots[M.cur] .. "f)") end
  end
  ctx.actions.trigger = function()
    for i, t in ipairs(TRIGGERS) do
      if t == M.trigger then M.trigger = TRIGGERS[(i % #TRIGGERS) + 1]; break end
    end
    if not ctx.headless then emu.displayMessage("training", "trigger: " .. M.trigger) end
  end

  -- ---- auto-trigger detection ----
  -- Runs at the TOP of the input stage (inputPolled), where ctx.snap is the last fully
  -- CLASSIFIED frame — a plain frame hook here would run before framedata sets cls and
  -- never see constraints (the same ordering trap dummy.lua hit).
  local CONSTRAINED = {}
  do
    local CLS = C.CLS
    CONSTRAINED[CLS.HITSTUN] = "hitstun"; CONSTRAINED[CLS.BLOCKSTUN] = "blockstun"
    CONSTRAINED[CLS.KNOCKDOWN] = "wakeup"; CONSTRAINED[CLS.THROWN] = "wakeup"
  end
  local wasConstraint = nil
  local function autoTrigger()
    if M.state ~= "idle" then return end
    local s = ctx.snap
    if not s then return end
    local d = s.p[dummyPort]
    local con = CONSTRAINED[d.cls]
    -- predictive fire: the LAST constrained frames before freedom aren't knowable ahead
    -- of time in general; instead we rely on the engine's press-latch — firing on the
    -- first free frame's input poll is frame-perfect for move starts.
    if wasConstraint and not con then
      if (M.trigger == "wakeup" and wasConstraint == "wakeup")
         or (M.trigger == "blockstun" and wasConstraint == "blockstun")
         or (M.trigger == "hitstun" and wasConstraint == "hitstun")
         or (M.trigger == "random" and wasConstraint ~= nil) then
        startPlay()
      end
    end
    -- GC trainer: fire on blockstun ENTRY so the motion resolves inside the stun
    if M.trigger == "gc" and con == "blockstun" and wasConstraint ~= "blockstun" then
      if M.gcChance >= 100 or math.random(100) <= M.gcChance then startPlay() end
    end
    if M.trigger == "loop" and M.state == "idle" then startPlay() end
    wasConstraint = con
  end

  -- ---- input pipeline stage ----
  local function stage()
    autoTrigger()
    local onLeftD = gs.onLeft(dummyPort)
    if M.state == "armed" or M.state == "recording" then
      -- the user's pad (already routed to the dummy port by pad-swap) is the source
      local pad = ctx.pads.eff[dummyPort]
      local mask = input.maskOf(pad, onLeftD)
      if M.state == "armed" and mask ~= 0 then M.state = "recording" end
      if M.state == "recording" then
        local sl = M.slots[M.cur]
        sl[#sl + 1] = mask
      end
    elseif M.state == "playing" then
      local sl = M.slots[M.playSlot]
      if M.playPos > #sl then
        M.state = "idle"
        if M.trigger == "loop" then startPlay() end
      else
        ctx.out[dummyPort] = input.padOf(sl[M.playPos], onLeftD)
        M.playPos = M.playPos + 1
      end
    end
  end

  table.insert(ctx.hooks.input, stage)
  table.insert(ctx.hooks.reset, function()
    if M.state == "playing" then M.state = "idle" end
    wasConstraint = nil
  end)
end

return M
