#!/usr/bin/env python3
"""Generate tools/README.md — a one-line-per-script index of everything in tools/,
harvested from each file's first header-comment line (issue #53: 190+ flat files,
three naming schemes, no index). Re-run after adding or renaming tools.

Usage: python3 tools/mkindex.py        (rewrites tools/README.md)
"""
from pathlib import Path as _P
import re

REPO = _P(__file__).resolve().parent.parent
TOOLS = REPO / "tools"

GROUPS = [
    ("Builders (mkpatch*)", r"^mkpatch"),
    ("Build/distribution scripts", r"^(build_|mkdist|mkindex|run\.sh)"),
    ("Shared libraries", r"^(sms_env|smspaths|asm65816|hudfont|texttiles)\."),
    ("Test suites & oracles", r"^(test_|training_test)"),
    ("Demos & measurement workhorses", r"^(demo_|react_|techsweep|techfind|trace|coltest|escape_matrix|ds_|trainer)"),
    ("Training mode (Lua package entry)", r"^training"),
    ("Probes (one-shot investigation scripts)", r"^(probe_|perf_|nav|inputprobe|capcheck|wramdump|mockup)"),
    ("Extractors", r"^extract_"),
]


def first_comment(path):
    try:
        text = path.read_text(errors="replace")
    except Exception:
        return ""
    for ln in text.splitlines()[:6]:
        s = ln.strip()
        if s.startswith("--"):
            return s.lstrip("-").strip()
        if s.startswith("#") and not s.startswith("#!"):
            return s.lstrip("#").strip()
        if s.startswith('"""'):
            return s.strip('"').strip()
    return ""


def main():
    files = sorted(p for p in TOOLS.iterdir()
                   if p.is_file() and p.suffix in (".py", ".lua", ".sh") and p.name != "README.md")
    grouped, used = {}, set()
    for title, pat in GROUPS:
        rx = re.compile(pat)
        grouped[title] = [p for p in files if rx.match(p.name) and p.name not in used]
        used.update(p.name for p in grouped[title])
    leftover = [p for p in files if p.name not in used]
    if leftover:
        grouped["Other"] = leftover

    out = ["# tools/ index",
           "",
           "GENERATED by `python3 tools/mkindex.py` from each script's first header line —",
           "regenerate after adding tools; do not edit by hand. Cfg convention: `<name>_cfg.lua`",
           "is the optional knob file `<name>.lua` loads. See HANDOFF.md §4 for the harness.",
           ""]
    for title, ps in grouped.items():
        if not ps:
            continue
        out.append(f"## {title}")
        out.append("")
        for p in ps:
            desc = first_comment(p)
            desc = re.sub(r"^" + re.escape(p.name) + r"\s*[—-]*\s*", "", desc)
            out.append(f"- `{p.name}` — {desc}" if desc else f"- `{p.name}`")
        out.append("")
    (TOOLS / "README.md").write_text("\n".join(out) + "\n")
    print(f"wrote tools/README.md ({len(files)} scripts, {len(grouped)} groups)")


if __name__ == "__main__":
    main()
