#!/usr/bin/env python3
"""Generate tools/README.md — a one-line-per-script index of everything in tools/,
harvested from each file's first header-comment line (issue #53: 190+ flat files,
three naming schemes, no index). Recursive since #103: tools/saturn/ and
tools/training/ get their own sections (vendored trees — Mesen.app, Dispel,
Flips — are excluded). Re-run after adding or renaming tools.

Usage: python3 tools/mkindex.py            (rewrites tools/README.md)
       python3 tools/mkindex.py --check    (exit 1 if the committed index is stale;
                                            run by build_v022.sh / build_ref_v*.sh / health.sh)
"""
from pathlib import Path as _P
import re
import sys

sys.path.insert(0, str(_P(__file__).resolve().parent))
from cliguard import reject_unknown_flags

REPO = _P(__file__).resolve().parent.parent
TOOLS = REPO / "tools"

# vendored / binary trees that must not be indexed
EXCLUDE_PARTS = {"Mesen.app", "Dispel", "Flips"}

# matched against the path RELATIVE to tools/ (subtree groups first — the
# name-anchored patterns below would otherwise never see 'saturn/…' paths)
GROUPS = [
    ("Saturn port tooling (tools/saturn/)", r"^saturn/"),
    ("Training mode (Lua package, tools/training/)", r"^training/"),
    ("Builders (mkpatch*)", r"^mkpatch"),
    ("Build/distribution scripts", r"^(build_|mkdist|mkindex|mkrelease|mksigs|health|run\.sh)"),
    ("Shared libraries", r"^(sms_env|smspaths|asm65816|hudfont|texttiles|probelib)\."),
    ("Test suites & oracles", r"^(test_|training_test)"),
    ("Demos & measurement workhorses", r"^(demo_|react_|techsweep|techfind|trace|coltest|escape_matrix|ds_|trainer)"),
    ("Training mode (Lua package entry)", r"^training"),
    ("Probes (one-shot investigation scripts)", r"^(probe_|perf_|nav|inputprobe|capcheck|wramdump|mockup)"),
    ("Extractors", r"^extract_"),
]


def first_comment(path):
    try:
        text = path.read_text(errors="replace")
    except OSError as e:
        print(f"mkindex: WARNING: cannot read {path}: {e}", file=sys.stderr)
        return ""
    for ln in text.splitlines()[:6]:
        s = ln.strip()
        if s.startswith("--"):
            return s.lstrip("-").strip()
        if s.startswith("#") and not s.startswith("#!"):
            return s.lstrip("#").strip()
        if s.startswith('"""'):
            return s.strip('"').strip()
    return ""


def render():
    files = sorted(
        (p for p in TOOLS.rglob("*")
         if p.is_file() and p.suffix in (".py", ".lua", ".sh")
         and not (EXCLUDE_PARTS & set(p.parts))),
        key=lambda p: str(p.relative_to(TOOLS)))
    grouped, used = {}, set()
    for title, pat in GROUPS:
        rx = re.compile(pat)
        grouped[title] = [p for p in files
                          if rx.match(str(p.relative_to(TOOLS))) and p not in used]
        used.update(grouped[title])
    leftover = [p for p in files if p not in used]
    if leftover:
        grouped["Other"] = leftover

    out = ["# tools/ index",
           "",
           "GENERATED by `python3 tools/mkindex.py` from each script's first header line —",
           "regenerate after adding tools; do not edit by hand (`--check` verifies sync).",
           "Cfg convention: `<name>_cfg.lua` is the optional knob file `<name>.lua` loads.",
           "See HANDOFF.md §4 for the harness.",
           ""]
    nfiles = 0
    for title, ps in grouped.items():
        if not ps:
            continue
        out.append(f"## {title}")
        out.append("")
        for p in ps:
            rel = str(p.relative_to(TOOLS))
            desc = first_comment(p)
            desc = re.sub(r"^" + re.escape(p.name) + r"\s*[—-]*\s*", "", desc)
            out.append(f"- `{rel}` — {desc}" if desc else f"- `{rel}`")
            nfiles += 1
        out.append("")
    return "\n".join(out) + "\n", nfiles, len(grouped)


def main():
    # ⚠ The sharpest case of the three. --check is tested with `in sys.argv`, so
    # a typo does not fail — it falls through to the WRITE branch, regenerates
    # tools/README.md and prints "wrote ...". In CI that reads like the
    # staleness check passing while it quietly erases the drift it exists to
    # report (trap 17 with the safety catch removed).
    reject_unknown_flags(sys.argv, {"--check"}, "mkindex.py")
    text, nfiles, ngroups = render()
    target = TOOLS / "README.md"
    if "--check" in sys.argv:
        current = target.read_text() if target.exists() else ""
        if current != text:
            print("mkindex: error: tools/README.md is out of date — run: python3 tools/mkindex.py",
                  file=sys.stderr)
            raise SystemExit(1)
        print(f"tools/README.md in sync ({nfiles} scripts, {ngroups} groups)")
        return
    target.write_text(text)
    print(f"wrote tools/README.md ({nfiles} scripts, {ngroups} groups)")


if __name__ == "__main__":
    main()
