#!/usr/bin/env python3
"""mkrelease.py — render release/RELEASE_NOTES.md from the files that exist.

Why generated rather than written: this project has already shipped three STALE
doc hashes, caught only by an audit (HANDOFF, 2026-07-30). Release notes are the
one document a player acts on, so every hash and size in them is measured here at
render time, and a patch whose .bps is missing is reported as missing instead of
silently dropped.

What it does NOT do: build anything. Run `tools/build_rev.sh both` first; this
reads `release/Rev.S-XX.bps` / `release/Rev.SS-XX.bps` and the per-patch
standalones in `build/`, then writes the notes.

  python3 tools/mkrelease.py            # render for smspaths.REV_S / REV_SS
  python3 tools/mkrelease.py --rev-s 02 --rev-ss 03
  python3 tools/mkrelease.py --check    # exit 1 if the notes are out of date
"""
import argparse
import hashlib
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
import smspaths  # noqa: E402

# The individual patches, newest builder output each. Order = the registry's.
# (id, title, builder invocation, standalone bps)
PATCHES = [
    ("1",   "Infinite -> 1-frame meaty (canonical gate)", "mkpatch.py 0x04", "sms_uranus_infinite_1f.bps"),
    ("1b",  "Infinite -> true 1-frame combo (alt gate)", "mkpatch.py 0x05", "sms_uranus_infinite_1f_truecombo.bps"),
    ("2",   "Remove reversal-dash invincibility", "mkpatch2.py", "sms_dashfix.bps"),
    ("3",   "Big Zam extended palettes + ROM header", "mkpatch3.py", "sms_palettes.bps"),
    ("4",   "Title subtitle + BZ credit line", "mkpatch4.py", "sms_title.bps"),
    ("5",   "Uranus forward-dash distance -1/3", "mkpatch5.py", "sms_dashdist.bps"),
    ("6",   "Uranus forward-dash i-frames (experimental)", "mkpatch6.py", "sms_dashinvuln.bps"),
    ("7",   "Pluto 5HP hits crouchers", "mkpatch7.py", "sms_pluto5hp.bps"),
    ("8",   "Venus 6HP throw tech window 6f -> 13f", "mkpatch8.py", "sms_venustech.bps"),
    ("9",   "Neptune Deep Submerge hitbox tracks the ball", "mkpatch9.py", "sms_neptune_ds.bps"),
    ("10",  "In-match combo counter", "mkpatch10.py", "sms_combocounter.bps"),
    ("10b", "Combo counter + status labels", "mkpatch10.py --events labels", "sms_combolabels.bps"),
    ("11",  "In-ROM training mode (L+R menu)", "mkpatch11.py", "sms_trainingplus.bps"),
    ("12",  "Taunts on L", "mkpatch12.py", "sms_taunt.bps"),
    ("13",  '"Guts" — taunt completion nerfs specials', "mkpatch13.py", "sms_tauntbuff.bps"),
    ("14",  '"Guts Grip" — same for command grabs (needs 13)', "mkpatch14.py", "sms_gutsgrip.bps"),
    ("15",  "Remove the AUTO option", "mkpatch15.py", "sms_noauto.bps"),
    ("17",  "All stages selectable (hidden stage)", "mkpatch17.py", "sms_allstages.bps"),
    ("18",  "No ACS in 2P VS", "mkpatch18.py", "sms_noacs_vs.bps"),
]

# What each reference carries, for the notes. Kept next to the builder that
# produces them so the two cannot drift apart unnoticed.
REV_S_CONTENT = "1b + 2 + 3 + 4 + 5 + 7 + 8 + 9 + 12 + 13 + 14 + 15 + 18"
REV_SS_CONTENT = REV_S_CONTENT + " + Saturn (patch 100/101 + her ported stage)"


def sha1(p):
    return hashlib.sha1(p.read_bytes()).hexdigest()


def render(rev_s, rev_ss):
    rel = REPO / "release"
    s, ss = rel / f"Rev.S-{rev_s}.bps", rel / f"Rev.SS-{rev_ss}.bps"
    out = [f"# Releases — Rev. S-{rev_s} and Rev. SS-{rev_ss}", "",
           "Apply a `.bps` to the **clean Japanese ROM** with Flips (or any BPS",
           "patcher). Clean ROM SHA-1 `bc0e29ee383574443226695215496eb0d09aaa1c`",
           "(HiROM+FastROM, headerless, **2.5 MB** — 40 banks, $C0-$E7; the patched",
           "output is 3 MB because the patches append banks). ROMs are never",
           "distributed here.", "",
           "*Generated by `tools/mkrelease.py` — every hash below is measured from the",
           "file it names, never transcribed.*", "",
           "## The two reference builds", "",
           "Start here. Each is a complete build; you do not stack anything onto it.", "",
           "| Build | What it is | Patch file | Patched ROM SHA-1 |", "|---|---|---|---|"]

    def refrow(path, name, what, content, rev):
        if not path.exists():
            return f"| **{name}** | {what} | **MISSING** | run `tools/build_rev.sh` |"
        romname = ("SailorMoonS_Rev_S-" if "SS" not in name else "SailorMoonS_Rev_SS-") + rev + ".sfc"
        rom = REPO / "build" / romname
        romsha = f"`{sha1(rom)[:8]}…`" if rom.exists() else "*(rebuild to see)*"
        return (f"| **{name}** | {what}<br>{content} | "
                f"`{path.relative_to(REPO)}` (`{sha1(path)[:8]}…`) | {romsha} |")

    out.append(refrow(s, f"Rev. S-{rev_s}",
                      "the reference build, **no Super S content**", REV_S_CONTENT, rev_s))
    out.append(refrow(ss, f"Rev. SS-{rev_ss}",
                      "the same, **plus Sailor Saturn**", REV_SS_CONTENT, rev_ss))
    out += ["",
            f"The title screen reads **FrenchName Rev. S-{rev_s}** /",
            f"**FrenchName Rev. SS-{rev_ss}** —",
            "that string is the naked-eye tell; quote it (or the ROM SHA-1) in any",
            "report. `Rev. SS` also answers to L+R held while confirming a Uranus,",
            "Neptune or Pluto slot: that is how Saturn is summoned.", "",
            "**The shared patch chain is the same bytes in both** — `tools/build_rev.sh`",
            "builds them from one chain, so the non-Saturn common part cannot drift.",
            f"The revisions differ (**S-{rev_s} vs SS-{rev_ss}**) only because a change to",
            "Saturn — her round-won badge — moved the SS bytes and not the S bytes; a",
            "revision names one set of bytes for good, so only the side that changed",
            "gets a new number.",
            "", "## The individual patches", "",
            "For building your own combination. Chain the *builders* (each re-detects",
            "the next free bank) — **never chain the standalone `.bps` files**, since",
            "every bank-appending patch targets the same first free bank and would",
            "overwrite the previous one. Each row's patch is diffed against the CLEAN",
            "ROM.", "",
            "| # | Patch | Builder | Standalone patch | .bps SHA-1 |", "|---|---|---|---|---|"]
    for pid, title, builder, bps in PATCHES:
        p = REPO / "build" / bps
        if p.exists():
            out.append(f"| {pid} | {title} | `tools/{builder}` | `build/{bps}` | `{sha1(p)[:8]}…` |")
        else:
            out.append(f"| {pid} | {title} | `tools/{builder}` | **MISSING** | — |")
    out += ["", "## Verifying a build", "", "```bash",
            f"tools/build_rev.sh both                                  # rebuild both references",
            f"ROM=build/SailorMoonS_Rev_S-{rev_s}.sfc tools/run.sh tools/test_regression.lua 900",
            f"ROM=build/SailorMoonS_Rev_SS-{rev_ss}.sfc tools/saturn/verify_saturn.sh",
            "```", "",
            "The first is the engine + per-patch regression suite; the second is the",
            "Saturn gate, which runs that suite first and then the Super S matrix.", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--rev-s", default=None, help="S revision (default: smspaths.REV_S)")
    ap.add_argument("--rev-ss", default=None, help="SS revision (default: smspaths.REV_SS)")
    ap.add_argument("--check", action="store_true", help="exit 1 if the notes are stale")
    a = ap.parse_args()
    rev_s = a.rev_s or smspaths.REV_S
    rev_ss = a.rev_ss or smspaths.REV_SS
    text = render(rev_s, rev_ss)
    notes = REPO / "release" / "RELEASE_NOTES.md"
    if a.check:
        if not notes.exists():
            sys.stderr.write("error: release/RELEASE_NOTES.md does not exist — "
                             "run: python3 tools/mkrelease.py\n")
            raise SystemExit(1)
        have = notes.read_text()
        if have != text:
            # The ROM SHA-1 column can only be regenerated where the built .sfc
            # files are present, and they are gitignored — so on a fresh clone or
            # a CI runner this check used to fail for a reason that says nothing
            # about the notes. Compare the rest, and say what was not compared.
            def strip_rom_rows(t):
                return [ln for ln in t.splitlines() if "| **Rev. " not in ln]
            if strip_rom_rows(have) == strip_rom_rows(text):
                print(f"release notes in sync (Rev. S-{rev_s} / SS-{rev_ss}) — except the two ROM SHA-1 "
                      "cells, which need the built .sfc files (absent here)")
                return
            sys.stderr.write("error: release/RELEASE_NOTES.md is out of date — "
                             "run: python3 tools/mkrelease.py\n")
            raise SystemExit(1)
        print(f"release notes in sync (Rev. S-{rev_s} / SS-{rev_ss})")
        return
    notes.parent.mkdir(exist_ok=True)
    notes.write_text(text)
    print(f"wrote {notes.relative_to(REPO)} for Rev. S-{rev_s} / SS-{rev_ss}")


if __name__ == "__main__":
    main()
