#!/usr/bin/env python3
"""mksigs.py — keep test_regression.lua's detection SIGS in sync with the builders.

Each mkpatchN.py exports SIG = [(file_offset, expected_byte), ...] — its own detection
fingerprint, restricted to bytes invariant across stub-layout and bank-stacking changes.
This tool renders the Lua SIGS table from those exports.

Why this exists (follow-up to #33's registry point): the suite's fingerprints used to be
a hand-maintained duplicate of builder hook knowledge, and they drift silently — on
2026-07-30 the #21 fix shifted patch 13's stub and the suite went green while skipping
all 11 p13 tests. Builders now OWN their fingerprint; this keeps the suite honest.

Usage:
  python3 tools/mksigs.py --check    # exit 1 if the Lua table is out of sync (CI-able;
                                     # run by build_v022.sh / build_ref_v1.sh)
  python3 tools/mksigs.py --write    # regenerate the block in test_regression.lua
"""
import importlib
import re
import sys
from pathlib import Path as _P

REPO = _P(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))

BUILDERS = {  # patch id -> module
    "p1": "mkpatch", "p2": "mkpatch2", "p3": "mkpatch3", "p4": "mkpatch4",
    "p5": "mkpatch5", "p6": "mkpatch6", "p7": "mkpatch7", "p8": "mkpatch8",
    "p9": "mkpatch9", "p10": "mkpatch10", "p11": "mkpatch11", "p12": "mkpatch12",
    "p13": "mkpatch13", "p14": "mkpatch14",
}
LUA = REPO / "tools/test_regression.lua"
BEGIN = "-- SIGS-BEGIN (generated by tools/mksigs.py from each builder's SIG — do not edit)"
END = "-- SIGS-END"


def render():
    lines = [BEGIN, "local SIGS = {"]
    for pid, mod in BUILDERS.items():
        sig = importlib.import_module(mod).SIG
        pairs = ", ".join("{ 0x%06X, 0x%02X }" % (off, val) for off, val in sig)
        note = "  -- gate byte 0x1BE23 handled below (#29)" if pid == "p1" else ""
        lines.append(f"  {pid} = {{ {pairs} }},{note}")
    lines.append("}")
    lines.append(END)
    return "\n".join(lines)


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    src = LUA.read_text()
    m = re.search(re.escape(BEGIN) + r".*?" + re.escape(END), src, re.S)
    if not m:
        raise SystemExit(f"error: SIGS sentinels not found in {LUA}")
    want = render()
    if mode == "--check":
        if m.group(0) != want:
            sys.stderr.write("error: test_regression.lua SIGS is OUT OF SYNC with the "
                             "builders' SIG exports.\nRun: python3 tools/mksigs.py --write\n")
            raise SystemExit(1)
        print("SIGS in sync (14 patches)")
    elif mode == "--write":
        LUA.write_text(src[:m.start()] + want + src[m.end():])
        print(f"wrote SIGS block into {LUA.name}")
    else:
        raise SystemExit(f"unknown mode {mode}; use --check or --write")


if __name__ == "__main__":
    main()
