-- test_regression.lua — unified regression suite (base game + per-patch).
--
-- PLAN / DESIGN
--   Layer 0 (static): PRG-ROM fingerprints auto-DETECT which of patches 1-13 are in
--     the loaded ROM (stable signature bytes extracted clean-vs-standalone-vs-stack);
--     damage-matrix integrity rows (0/10/48) asserted on every ROM (no patch may edit).
--   Layer 1 (base): engine invariants that must hold on ANY build (clean or stacked) —
--     deterministic damage rolls, counter-hit −2 columns, posture tables, proximity
--     normals, throw toss path, desperation types/totals (Jupiter strike, Uranus
--     hybrid+toss, Pluto drain grab, Neptune corrected input), dash distance and the
--     2HP→dash cancel gate (expectations switch on detected p5/p1).
--   Layer 2 (patch): nominal + edge cases per detected patch — p7 dual-mode (Pluto 5HP
--     hits crouching Mercury iff patched; Chibi still whiffs at default height), p8
--     dual-mode (mash at grab+14 techs iff patched; grab+4 always techs = base), p10
--     combo counter, p11 L+R menu + P1-HP-LOW navigation, p12 taunt (nominal, R-held
--     exclusion, act-gate edge), p13 Guts (grant, interrupt, special scaling, throw
--     exemption, Uranus toss, Pluto ticks, round-reset clears levels) and the
--     cross-patch counter-hit×Guts case (72 → 29, exercising the v3.3 wide tables).
--   Base also covers the full 9-character desperation compendium (types + totals) and
--     three crouch-mechanism edges (Uranus 51 hit-count, Mercury 62 column, Chibi 24).
--   Values are single-roll deterministic (fixed savestate + fixed input frames).
--
-- Config tools/test_regression_cfg.lua (optional):
--   EXPECT = "clean"|"all"  (assert detection result), ONLY = "pattern" (filter tests)
-- Output: traces/regression.txt, final line "ALL PASS (n)" or "FAILURES (k/n)".
local ENV = dofile((package.path:match("([^;]+)%?%.lua$") or error("sms_env: tools dir not in package.path")) .. "/sms_env.lua")
-- Config load (#82): probe for the file, then dofile it UNPROTECTED. `pcall` here
-- swallowed syntax errors, so a broken cfg silently produced a run with EXPECT and
-- ONLY unset — i.e. the gate you asked for just did not happen, and the suite still
-- printed ALL PASS. Absent is still silent; broken now aborts.
local CFG = ENV.TOOLS .. "test_regression_cfg.lua"
local cfgf = io.open(CFG, "r")
if cfgf then cfgf:close(); dofile(CFG) end
if EXPECT ~= nil and EXPECT ~= "clean" and EXPECT ~= "all" then
  error(string.format("test_regression_cfg.lua: EXPECT must be \"clean\" or \"all\", got %q", tostring(EXPECT)))
end
local TRACE = ENV.TRACE
-- TRUNCATE, do not append (#81). The consumers of this file — verify_saturn.sh's
-- `check()` and every human running `tail -1` — read the LAST matching line. In
-- append mode a run that died before writing a verdict left the previous run's
-- "ALL PASS" as that line, so the gate reported PASS for a run that never happened.
local LOG = assert(io.open(TRACE .. "regression.txt", "w"))
local function log(s) LOG:write(s .. "\n"); LOG:flush() end
local PL = ENV.dofile("probelib.lua")   -- shared emulator-access helpers (#34)
local WRAM, PRG = PL.WRAM, PL.PRG
local ram, wr, rom = PL.ram, PL.wr, PL.rom

-- ===== Layer 0: fingerprints =====
-- SIGS-BEGIN (generated by tools/mksigs.py from each builder's SIG — do not edit)
local SIGS = {
  p1 = { { 0x01874D, 0x20 }, { 0x01874E, 0xBE }, { 0x01BE22, 0xC9 } },  -- gate byte 0x1BE23 handled below (#29)
  p2 = { { 0x0188ED, 0x2A }, { 0x0188EE, 0xBE }, { 0x01BE2A, 0x20 } },
  p3 = { { 0x00884B, 0xA9 }, { 0x00884C, 0x0C }, { 0x00884F, 0x65 } },
  p4 = { { 0x03B820, 0x00 }, { 0x03B821, 0x00 } },
  p5 = { { 0x0188EA, 0x40 }, { 0x0188EB, 0x06 } },
  p6 = { { 0x009CCD, 0x22 }, { 0x009CCE, 0x85 }, { 0x009CCF, 0xBE } },
  p7 = { { 0x0AF0DE, 0x3E } },
  p8 = { { 0x016C70, 0x01 } },
  p9 = { { 0x0AFD5D, 0xF5 }, { 0x0AFD65, 0xF5 }, { 0x0AFD6D, 0xF5 } },
  p10 = { { 0x00D56F, 0x5C }, { 0x00D5E8, 0x5C } },
  p11 = { { 0x008373, 0x5C } },
  p12 = { { 0x008377, 0x5C } },
  p13 = { { 0x00837B, 0x5C }, { 0x00C09C, 0x22 }, { 0x00C16F, 0x22 } },
  p14 = { { 0x010835, 0x22 }, { 0x010839, 0xB0 }, { 0x010D5A, 0x22 } },
  p15 = { { 0x03A863, 0xEA }, { 0x03A880, 0x80 } },
  p17 = { { 0x03BADE, 0x9C } },
  p18 = { { 0x03BB9E, 0xA5 }, { 0x03BBA0, 0x3A } },
}
-- SIGS-END
-- Patch ids to report and gate on, DERIVED from SIGS (#83). These three loops used
-- to be written `for i = 1, 14`, so every patch added after p14 was invisible to the
-- detect line and to both EXPECT gates — by the time this was fixed the hole was
-- three patches wide (15, 17, 18), exactly as the issue predicted. Adding a
-- fingerprint is now the only step needed to bring a new patch under the gates.
local PATCH_IDS = {}
for pn in pairs(SIGS) do
  local n = tonumber(pn:match("^p(%d+)$"))
  if n then PATCH_IDS[#PATCH_IDS + 1] = { n = n, id = pn } end
end
table.sort(PATCH_IDS, function(x, y) return x.n < y.n end)
-- projectile-desperation dispatcher records (file offsets, 7 bytes each)
local DESP_RECORDS = {
  { 0x1375A, "0c000000c0ff00" },  -- Moon
  { 0x1586D, "11011800000000" },  -- Mars
  { 0x179D9, "16004000000000" },  -- Venus
  { 0x1BDFE, "1b011000ecff00" },  -- Chibi
}
local CHARLOADER_OFF = 0x87D0
local CHARLOADER_HEX = "9c0610ad081d8d7010ad091d8d7110ad0a1d8d7210ad0b1d8d7310ad0c1d8d7410ad0d1d8d7510ad72100a0a0a1869608d49108d4a10c220a980008d2110a9c0008d25109c0a10a901008d12109c30109c32109c34109c36109c38109c3a109c7910bf3802e08520e220a720e6208d4810c220ad02"
local MOD_HANDLERS_OFF = 0xCAED
local MOD_HANDLERS_HEX = "c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5703a1865008500b5454c55d0c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5733a1865008500b5454c55d0c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5743a1865008500b5454c55d0c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5701865008500b5454c55d0c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5731865008500b5454c55d0c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5741865008500b5454c55d0c210e220a688a422640060c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5731865008500b5452055d0e220a5004a4ad002a901850060c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5741865008500b5452055d0e220a5004a4ad002a901850060c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5743a1865008500b5452055d0e220b94900c500b002850060c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5741865008500b5452055d0e220b94900c500b002850060c210e220a58dc904d0034c6acda688a4226400b918002901f004a9fe8500b948001879710038f5741865008500b5452055d0e220a5004a4ad002a9018500b94900c500b002850060c210e2"
local MATRIX_ROWS = {
  [0] = { 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 },
  [10] = { 0x15, 0x15, 0x14, 0x14, 0x13, 0x11, 0x0F, 0x0D, 0x0A, 0x08, 0x07, 0x06, 0x05, 0x05, 0x05, 0x05 },
  [48] = { 0x48, 0x48, 0x48, 0x48, 0x48, 0x48, 0x48, 0x3E, 0x30, 0x25, 0x20, 0x1C, 0x1A, 0x18, 0x18, 0x17 },
}
local has = {}

-- ===== harness =====
local t, needLoad, stateFile = -1, false, nil
local results, curTest, testT0 = {}, nil, 0
local pulse = {}
local hits = {}
local hpSeed = {}   -- live HP at test start, per address (issue #16)

emu.addMemoryCallback(function()
  if needLoad and stateFile then
    local f = assert(io.open(TRACE .. stateFile, "rb"))
    emu.loadSavestate(f:read("*a")); f:close()
    needLoad = false
  end
end, emu.callbackType.exec, 0x808353, 0x808353, emu.cpuType.snes, emu.memType.snesMemory)

for _, a in ipairs({ 0x1049, 0x10C9 }) do
  emu.addMemoryCallback(function(addr, value)
    if curTest then
      local st = emu.getState()
      local pc = st["cpu.k"] * 65536 + st["cpu.pc"]
      local lo = pc % 0x10000
      local kind = "other"
      if pc >= 0x80C000 and pc < 0x80C300 then kind = "MELEE"
      elseif pc >= 0x80C300 and pc < 0x80C700 then kind = "PROJ"
      elseif lo >= 0x0D50 and lo <= 0x0D70 then kind = "TICK"
      elseif lo >= 0x0820 and lo <= 0x0870 then kind = "TOSS"
      elseif pc >= 0xC80000 then kind = "GRAB" end   -- p14 relocates grab stores to its bank
      hits[#hits + 1] = { pt = t - testT0, addr = addr % 0x10000, v = value, pc = pc,
        kind = kind, a1 = ram(0x1044), a2 = ram(0x10C4), act1 = ram(0x1001), act2 = ram(0x1081) }
    end
  end, emu.callbackType.write, a, a, emu.cpuType.snes, emu.memType.snesWorkRam)
end

emu.addEventCallback(function()
  for p = 0, 1 do
    emu.setInput(PL.pad(pulse[p]), 0, p)   -- shared all-false pad + overrides (#78)
  end
end, emu.eventType.inputPolled)

-- helpers -----------------------------------------------------------------
local function struct(p) return (p == 1) and 0x1000 or 0x1080 end
local function posx(b) return ram(b + 0x21) + 256 * ram(b + 0x22) end
local function setx(b, x) wr(b + 0x21, x % 256); wr(b + 0x22, math.floor(x / 256)) end
local function park(att, range)          -- defender parked `range` px from attacker
  local ab, db = struct(att), struct(3 - att)
  local ax = posx(ab)
  local L = ax <= posx(db)
  setx(db, L and (ax + range) or (ax - range))
  wr(db + 0x49, 0x60); wr(0x800 + (2 - att), 0x60)
end
local function onLeft(att)
  return posx(struct(att)) <= posx(struct(3 - att))
end
local function dirpad(c, L)
  local m = { down = (c == "1" or c == "2" or c == "3"), up = (c == "7" or c == "8" or c == "9") }
  local fwd = (c == "3" or c == "6" or c == "9")
  local back = (c == "1" or c == "4" or c == "7")
  if fwd then if L then m.right = true else m.left = true end end
  if back then if L then m.left = true else m.right = true end end
  return m
end
-- motion driver: from pt0, `stepf` frames per step (default 3), button on step n+1
local function motion(api, player, mstr, btn, pt0, neutralBtn, stepf)
  local pt = api.pt
  local L = onLeft(player)
  local sd = math.floor((pt - pt0) / (stepf or 3)) + 1
  if pt >= pt0 and sd <= #mstr then
    pulse[player - 1] = dirpad(mstr:sub(sd, sd), L)
  elseif pt >= pt0 and sd == #mstr + 1 then
    local p = neutralBtn and {} or dirpad(mstr:sub(#mstr, #mstr), L)
    p[btn] = true
    pulse[player - 1] = p
  elseif pt >= pt0 and sd == #mstr + 2 then
    pulse[player - 1] = nil
  end
end
-- Per-address damage streams (issue #16): each player's HP walk is tracked against
-- its own previous value, seeded from live RAM at test start (testT0) rather than a
-- hardcoded 0x60. total() sums both players by default; total(1)/total(2) isolate one.
local function total(player)
  local tot, byk = 0, {}
  local prev = { [0x1049] = hpSeed[0x1049] or 0x60, [0x10C9] = hpSeed[0x10C9] or 0x60 }
  local want = player and ((player == 1) and 0x1049 or 0x10C9) or nil
  for _, h in ipairs(hits) do
    local d = (prev[h.addr] or 0x60) - h.v; prev[h.addr] = h.v
    if d > 0 and (not want or h.addr == want) then
      tot = tot + d; byk[h.kind] = (byk[h.kind] or 0) + d
    end
  end
  return tot, byk
end
local function ck(cond, msg) return cond, msg end
local function grabsum(byk) return (byk.TOSS or 0) + (byk.TICK or 0) + (byk.GRAB or 0) end
local function grabwrites()
  local n = 0
  for _, h in ipairs(hits) do if h.kind == "TICK" or h.kind == "TOSS" or h.kind == "GRAB" then n = n + 1 end end
  return n
end

-- ===== test list =====
-- spec: name, group ("base"|"pN"|"stack"), need = fn()->bool|nil, state, dur,
--        frame(api), verdict(api) -> ok, detail
local T = {}
local function add(s) T[#T + 1] = s end

-- Layer 1: base --------------------------------------------------------------
add{ name = "base-damage-determinism", group = "base", state = "uranus_vs_jupiter.mss", dur = 80,
  frame = function(api)
    if api.pt == 5 then park(1, 40) end
    if api.pt >= 30 and api.pt <= 31 then pulse[0] = { x = true } elseif api.pt == 32 then pulse[0] = nil end
  end,
  verdict = function() return ck(#hits == 1 and hits[1].v == 0x58, "5HP idle expects dmg 8, got " .. tostring(hits[1] and (0x60 - hits[1].v))) end }

add{ name = "base-counterhit-minus2col", group = "base", state = "uranus_vs_jupiter.mss", dur = 80,
  frame = function(api)
    if api.pt == 5 then park(1, 40) end
    if api.pt >= 30 and api.pt <= 31 then pulse[0] = { x = true } elseif api.pt == 32 then pulse[0] = nil end
    if api.pt >= 40 and api.pt <= 41 then pulse[1] = { x = true } elseif api.pt == 42 then pulse[1] = nil end
  end,
  verdict = function() return ck(#hits == 1 and 0x60 - hits[1].v == 12, "counter 5HP expects 12, got " .. tostring(hits[1] and (0x60 - hits[1].v))) end }

add{ name = "base-posture-stand", group = "base", state = "uranus_vs_jupiter.mss", dur = 80,
  frame = function(api)
    if api.pt == 5 then park(1, 30) end
    if api.pt >= 26 and api.pt <= 36 then
      local p = { down = true }; if api.pt >= 30 and api.pt <= 31 then p.x = true end
      pulse[0] = p
    elseif api.pt == 37 then pulse[0] = nil end
  end,
  verdict = function() return ck(#hits == 1 and 0x60 - hits[1].v == 5, "2HP vs stand expects 5, got " .. tostring(hits[1] and (0x60 - hits[1].v))) end }

add{ name = "base-posture-crouch", group = "base", state = "uranus_vs_jupiter.mss", dur = 80,
  frame = function(api)
    if api.pt == 5 then park(1, 30) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    if api.pt >= 26 and api.pt <= 36 then
      local p = { down = true }; if api.pt >= 30 and api.pt <= 31 then p.x = true end
      pulse[0] = p
    elseif api.pt == 37 then pulse[0] = nil end
  end,
  verdict = function() return ck(#hits == 1 and 0x60 - hits[1].v == 7, "2HP vs crouch expects 7, got " .. tostring(hits[1] and (0x60 - hits[1].v))) end }

add{ name = "base-proximity-normal", group = "base", state = "uranus_vs_jupiter.mss", dur = 80,
  frame = function(api)
    if api.pt == 5 then park(1, 34) end
    if api.pt >= 30 and api.pt <= 31 then pulse[0] = { x = true } elseif api.pt == 32 then pulse[0] = nil end
  end,
  verdict = function() return ck(#hits == 1 and 0x60 - hits[1].v == 9, "near-5HP expects 9, got " .. tostring(hits[1] and (0x60 - hits[1].v))) end }

add{ name = "base-throw-toss20", group = "base", state = "neptune_vs_jupiter.mss", dur = 120,
  frame = function(api)
    if api.pt == 5 then park(1, 14) end
    if api.pt >= 14 and api.pt <= 17 then
      local p = { x = true }; if onLeft(1) then p.right = true else p.left = true end
      pulse[0] = p
    elseif api.pt == 18 then pulse[0] = nil end
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 20 and grabsum(byk) == 20 and hits[1] and hits[1].a1 == 0,
      string.format("throw expects grab-path 20 a44=0, got tot=%d grab=%d a44=%02X", tot, grabsum(byk), hits[1] and hits[1].a1 or 255))
  end }

add{ name = "base-desp-jupiter-strike48", group = "base", state = "jupiter_vs_venus_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    motion(api, 1, "2141236", "x", 10, false)
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 48 and #hits == 1 and hits[1].kind == "MELEE",
      string.format("Jupiter desperation expects single MELEE 48, got tot=%d n=%d", tot, #hits))
  end }

add{ name = "base-desp-uranus-hybrid67", group = "base", state = "uranus_vs_jupiter.mss", dur = 380,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    motion(api, 1, "632141236", "a", 10, false)
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 67 and grabsum(byk) == 32,
      string.format("Uranus desperation expects 67 with toss 32, got tot=%d toss=%d", tot, grabsum(byk)))
  end }

add{ name = "base-desp-pluto-drain48", group = "base", state = "pluto_vs_1.mss", dur = 260,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    motion(api, 1, "632146", "x", 10, false)
  end,
  verdict = function()
    local tot, byk = total()
    local ticks = grabwrites()
    return ck(tot == 48 and ticks >= 10,
      string.format("Pluto desperation expects 48 with >=10 ticks, got tot=%d ticks=%d", tot, ticks))
  end }

add{ name = "base-desp-neptune-input37", group = "base", state = "neptune_vs_jupiter.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 60) end
    motion(api, 1, "6236236", "x", 10, true)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 37 and #hits == 1, string.format("Neptune desperation expects single 37, got tot=%d n=%d", tot, #hits))
  end }

-- dash distance / cancel gate: measured, expectation switches on p5/p1
local dashMeas = {}
add{ name = "base-dash-distance", group = "base", state = "uranus_vs_jupiter.mss", dur = 140,
  frame = function(api)
    if api.pt == 5 then park(1, 200) end
    if api.pt == 10 then dashMeas.x0 = posx(0x1000) end
    if api.pt == 12 or api.pt == 16 then pulse[0] = { [onLeft(1) and "right" or "left"] = true }
    elseif api.pt == 13 or api.pt == 17 then pulse[0] = nil end
    if api.pt == 120 then dashMeas.x1 = posx(0x1000) end
  end,
  verdict = function()
    local d = math.abs((dashMeas.x1 or 0) - (dashMeas.x0 or 0))
    local exp = has.p5 and 89 or 145
    return ck(math.abs(d - exp) <= 4, string.format("dash distance expects ~%d (p5=%s), got %d", exp, tostring(has.p5), d))
  end }

-- behavioural cancel-gate tests (issue #29): 2LP>2HP on hit, then the 66 dash input.
-- EARLY plan (66 taps complete at t=93, before vanilla's earliest cancel): vanilla
-- cancels immediately; the patch-1 gate makes the early input EXPIRE (no dash) — the
-- buffer removal itself. LATE plan (66 at 97/99, demo_link's keyframes): dash comes out
-- at hit+21 on vanilla AND gate 0x05, hit+22 on gate 0x04 (measured 2026-07-30,
-- tools/probe_cancelgate.lua; deterministic, exact frames).
local function cgFrame(late)
  return function(api)
    local m = api.mem
    if api.pt == 5 then wr(0x1021, 0xE8) end
    local kf = late and { {10,{down=true}}, {60,{down=true,y=true}}, {62,{down=true}},
                          {77,{down=true,x=true}}, {80,{down=true}},
                          {95,{}}, {97,{right=true}}, {98,{}}, {99,{right=true}}, {101,{}} }
                    or  { {10,{down=true}}, {60,{down=true,y=true}}, {62,{down=true}},
                          {77,{down=true,x=true}}, {80,{down=true}},
                          {89,{}}, {91,{right=true}}, {92,{}}, {93,{right=true}}, {95,{}} }
    local best = nil
    for _, e in ipairs(kf) do if e[1] <= api.pt then best = e[2] end end
    pulse[0] = best
    local a1, a2 = ram(0x1001), ram(0x1081)
    if api.pt > 78 and not m.hit and a2 >= 0x10 and a2 <= 0x18 then m.hit = api.pt end  -- 0x10..0x18 = ALL stun incl. flame 0x17/electric 0x18 (#99; authority: training/const.lua)
    if m.hit and not m.dash and a1 == 0x60 then m.dash = api.pt end
  end
end
add{ name = "base-cancelgate-early", group = "base", state = "uranus_vs_jupiter.mss", dur = 160,
  frame = cgFrame(false),
  verdict = function(api)
    local m = api.mem
    if not m.hit then return ck(false, "2HP never connected") end
    if has.p1 then
      return ck(m.dash == nil, string.format(
        "gated ROM must EXPIRE the early 66 (no buffering), but dash came out at +%s",
        tostring(m.dash and (m.dash - m.hit))))
    end
    return ck(m.dash and (m.dash - m.hit) == 16, string.format(
      "vanilla must cancel the early 66 at hit+16, got +%s", tostring(m.dash and (m.dash - m.hit))))
  end }
add{ name = "base-cancelgate-late", group = "base", state = "uranus_vs_jupiter.mss", dur = 160,
  frame = cgFrame(true),
  verdict = function(api)
    local m = api.mem
    if not m.hit then return ck(false, "2HP never connected") end
    local exp = (has.p1gate == 0x04) and 22 or 21
    return ck(m.dash and (m.dash - m.hit) == exp, string.format(
      "late 66 dash-out expects hit+%d (gate=%s), got +%s",
      exp, has.p1gate and string.format("%02X", has.p1gate) or "none",
      tostring(m.dash and (m.dash - m.hit))))
  end }

add{ name = "base-firsthit-defense-pair", group = "base", state = "uranus_vs_jupiter.mss", dur = 280,
  frame = function(api)
    if api.pt == 5 or api.pt == 205 then park(1, 40) end
    if (api.pt >= 30 and api.pt <= 31) or (api.pt >= 230 and api.pt <= 231) then pulse[0] = { x = true }
    elseif api.pt == 32 or api.pt == 232 then pulse[0] = nil end
  end,
  verdict = function()
    local ok = #hits == 2 and (0x60 - hits[1].v) == 8 and (0x60 - hits[2].v) == 10
    return ck(ok, string.format("first-hit defense: same move must deal 8 then 10 (d48 1->0), got %s/%s",
      hits[1] and (0x60 - hits[1].v), hits[2] and (0x60 - hits[2].v)))
  end }

add{ name = "base-throw-range-asymmetry", group = "base", state = "uranus_vs_jupiter.mss", dur = 280,
  frame = function(api)
    -- cycle 1 (facing right, distance 48): must grab; cycle 2 (facing left, 48): must whiff
    local c2 = api.pt >= 200
    local base = c2 and 200 or 0
    local rel = api.pt - base
    if rel >= 5 and rel <= 16 then
      local px0 = 0x0100
      wr(0x1020, 0); wr(0x1021, px0 % 256); wr(0x1022, math.floor(px0 / 256))
      local dx0 = c2 and (px0 - 48) or (px0 + 48)
      wr(0x10A0, 0); wr(0x10A1, dx0 % 256); wr(0x10A2, math.floor(dx0 / 256))
      wr(0x10C9, 0x60); wr(0x801, 0x60)
    end
    if rel >= 12 and rel <= 14 then
      local p = { a = true }
      if c2 then p.left = true else p.right = true end
      pulse[0] = p
    elseif rel == 15 then pulse[0] = nil end
    if not c2 and rel > 14 and rel < 60 and ram(0x1081) == 0x1C then api.mem.grabR = true end
    if c2 and rel > 14 and rel < 60 and ram(0x1081) == 0x1C then api.mem.grabL = true end
  end,
  verdict = function(api)
    return ck(api.mem.grabR == true and not api.mem.grabL,
      string.format("throw range asymmetry: 48px must grab facing right and whiff facing left (R=%s L=%s)", tostring(api.mem.grabR), tostring(api.mem.grabL)))
  end }

add{ name = "base-airok-throw-vertical-range", group = "base", state = "moon_vs_moon.mss", dur = 280,
  frame = function(api)
    -- cycle 1: Rabbit Flip (HK, air-OK) grabs a 24px-levitated target; cycle 2: Headbutt (HP) whiffs an 8px one
    local c2 = api.pt >= 200
    local base = c2 and 200 or 0
    local rel = api.pt - base
    if rel >= 5 and rel <= 16 then
      local px0 = 0x0100
      wr(0x1020, 0); wr(0x1021, px0 % 256); wr(0x1022, math.floor(px0 / 256))
      local dx0 = px0 + 20
      wr(0x10A0, 0); wr(0x10A1, dx0 % 256); wr(0x10A2, math.floor(dx0 / 256))
      local gy = 0xC0 - (c2 and 8 or 24)
      wr(0x10A4, 0); wr(0x10A5, gy % 256); wr(0x10A6, math.floor(gy / 256))
      wr(0x10C9, 0x60); wr(0x801, 0x60)
    end
    if rel >= 12 and rel <= 14 then
      pulse[0] = { right = true, [c2 and "x" or "a"] = true }
    elseif rel == 15 then pulse[0] = nil end
    if not c2 and rel > 14 and rel < 60 and ram(0x1081) == 0x1C then api.mem.grabFlip = true end
    if c2 and rel > 14 and rel < 60 and ram(0x1081) == 0x1C then api.mem.grabHead = true end
  end,
  verdict = function(api)
    return ck(api.mem.grabFlip == true and not api.mem.grabHead,
      string.format("air-OK vertical range: Flip must grab at 24px lift, Headbutt must whiff at 8px (F=%s H=%s)", tostring(api.mem.grabFlip), tostring(api.mem.grabHead)))
  end }

add{ name = "base-corner-chip-multiplier", group = "base", state = "venus_vs_jupiter_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 45); wr(0x10C8, 0) end
    if api.pt >= 6 then
      local p = {}
      if onLeft(1) then p.right = true else p.left = true end
      pulse[1] = p
      local px = posx(0x1000)
      setx(0x1080, px + 45); wr(0x10A0, 0)
    end
    motion(api, 1, "4123632", "x", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 60 and #hits == 5, string.format("frozen-defender (corner) blocked Chain Explosive expects 5x12=60, got %d in %d hits", tot, #hits))
  end }

add{ name = "base-desperation-clock-trigger", group = "base", state = "jupiter_vs_venus_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then park(1, 70); wr(0x803, 9); wr(0x804, 0) end
    motion(api, 1, "2141236", "x", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 48, "full-HP desperation must fire with clock <10s (timer poke), got " .. tot)
  end }

add{ name = "base-danger-threshold-0x18", group = "base", state = "uranus_vs_jupiter.mss", dur = 130,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x18); wr(0x801, 0x18) end
    if api.pt >= 6 and api.pt <= 12 and ram(0x1081) == 0x21 then api.mem.danger = true end
  end,
  verdict = function(api)
    return ck(api.mem.danger == true, "danger act 0x21 must fire on entering hp<=0x18")
  end }

add{ name = "base-death-chip-survives-at-0", group = "base", state = "neptune_vs_jupiter.mss", dur = 120,
  frame = function(api)
    if api.pt == 5 then park(1, 70); wr(0x10C9, 1); wr(0x801, 1) end
    if api.pt >= 6 then
      local p = {}
      if onLeft(1) then p.right = true else p.left = true end
      pulse[1] = p
    end
    motion(api, 1, "214", "y", 10, false)
    if api.pt > 30 and ram(0x1081) == 0x1F then api.mem.died = true end
  end,
  verdict = function(api)
    return ck(#hits == 1 and hits[1].v == 0 and not api.mem.died,
      string.format("chip 1 vs 1 HP must leave 0 HP ALIVE, got hp=%s died=%s", hits[1] and hits[1].v, tostring(api.mem.died)))
  end }

add{ name = "base-death-chip-underflow-kills", group = "base", state = "uranus_vs_jupiter.mss", dur = 200,
  frame = function(api)
    if api.pt == 5 then park(1, 70); wr(0x10C9, 1); wr(0x801, 1) end
    if api.pt >= 6 then
      local p = {}
      if onLeft(1) then p.right = true else p.left = true end
      pulse[1] = p
    end
    motion(api, 1, "632", "y", 10, false)
    if api.pt > 30 and ram(0x1081) == 0x1F then api.mem.died = true end
  end,
  verdict = function(api)
    return ck(api.mem.died == true, "chip 2 vs 1 HP must underflow-KO (act 0x1F), never died")
  end }

add{ name = "base-gc-gate-immediate", group = "base", state = "neptune_vs_jupiter.mss", dur = 80,
  frame = function(api)
    if api.pt == 5 then park(1, 36) end
    motion(api, 1, "214", "y", 10, false, 2)
    if api.pt >= 12 and api.pt <= 13 then pulse[1] = { x = true } elseif api.pt == 14 then pulse[1] = nil end
    local a = ram(0x1001)
    if (a == 0x0C or a == 0x0D or a == 0x0E or a == 0x0F) and not api.mem.stunAt then api.mem.stunAt = api.pt end
    if a == 0x62 and not api.mem.fireAt then api.mem.fireAt = api.pt end
  end,
  verdict = function(api)
    local ok = api.mem.stunAt and api.mem.fireAt and (api.mem.fireAt - api.mem.stunAt) <= 4
    return ck(ok, string.format("GC special must fire <=4f after blockstun (stun=%s fire=%s)", tostring(api.mem.stunAt), tostring(api.mem.fireAt)))
  end }

add{ name = "base-gc-backdash", group = "base", state = "uranus_vs_jupiter.mss", dur = 90,
  frame = function(api)
    if api.pt == 5 then park(1, 36) end
    if api.pt >= 12 and api.pt <= 13 then pulse[1] = { x = true } elseif api.pt == 14 then pulse[1] = nil end
    local back = onLeft(1) and "left" or "right"
    if api.pt >= 6 and api.pt <= 19 then pulse[0] = { [back] = true }
    elseif api.pt == 20 or api.pt == 21 then pulse[0] = nil
    elseif api.pt == 22 or api.pt == 23 then pulse[0] = { [back] = true }
    elseif api.pt == 24 then pulse[0] = nil
    elseif api.pt == 26 or api.pt == 27 then pulse[0] = { [back] = true }
    elseif api.pt == 28 then pulse[0] = nil end
    local a = ram(0x1001)
    if (a == 0x0C or a == 0x0E) and not api.mem.stun then api.mem.stun = true end
    if api.mem.stun and a == 0x26 and not api.mem.bd then api.mem.bd = api.pt end
  end,
  verdict = function(api)
    return ck(api.mem.stun and api.mem.bd and api.mem.bd < 45, "backdash must fire out of blockstun (GC), got " .. tostring(api.mem.bd))
  end }

add{ name = "base-prejump-throw-vulnerable", group = "base", state = "uranus_vs_jupiter.mss", dur = 60,
  frame = function(api)
    if api.pt == 5 then park(1, 14) end
    if api.pt >= 11 and api.pt <= 13 then pulse[1] = { up = true } elseif api.pt == 14 then pulse[1] = nil end
    if api.pt >= 13 and api.pt <= 16 then
      local p = { x = true }
      if onLeft(1) then p.right = true else p.left = true end
      pulse[0] = p
    elseif api.pt == 17 then pulse[0] = nil end
    if ram(0x1081) == 0x05 then api.mem.sawPrejump = true end
    if api.mem.sawPrejump and ram(0x1081) == 0x1C then api.mem.grabbedFromPrejump = true end
  end,
  verdict = function(api)
    return ck(api.mem.grabbedFromPrejump == true, "ground throw must grab a prejump defender (no throw invuln)")
  end }

-- Layer 2: patch-specific ----------------------------------------------------
add{ name = "p7-pluto5hp-vs-croucher", group = "p7", need = function() return true end,  -- dual-mode (Mercury: vanilla whiffs, p7 hits)
  state = "pluto_vs_2.mss", dur = 90,
  frame = function(api)
    if api.pt == 5 then park(1, 30) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    if api.pt >= 20 and api.pt <= 21 then local p = { x = true, down = false }; pulse[0] = p
    elseif api.pt == 22 then pulse[0] = nil end
  end,
  verdict = function()
    if has.p7 then return ck(#hits >= 1, "p7 present: Pluto 5HP must hit crouching Mercury, got no hits")
    else return ck(#hits == 0, "p7 absent: Pluto 5HP must whiff on crouching Mercury, got " .. #hits .. " hits") end
  end }

add{ name = "p7-chibi-still-whiffs", group = "p7", need = function() return has.p7 end,
  state = "pluto_vs_chibi_v07.mss", dur = 90,
  frame = function(api)
    if api.pt == 5 then park(1, 30) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    if api.pt >= 20 and api.pt <= 21 then pulse[0] = { x = true }
    elseif api.pt == 22 then pulse[0] = nil end
  end,
  verdict = function()
    return ck(#hits == 0, "p7 default h=62: crouching Chibi must still whiff, got " .. #hits .. " hits")
  end }

add{ name = "p9-ds-tracks-sprite", group = "p9", need = function() return true end,  -- dual-mode
  state = "neptune_vs_chibi.mss", dur = 90,
  frame = function(api)
    if api.pt == 5 then park(1, 70) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    motion(api, 1, "214", "y", 10, false)
  end,
  verdict = function()
    if #hits ~= 1 then return ck(false, "expected one DS contact vs crouching Chibi, got " .. #hits) end
    local t = hits[1].pt
    if has.p9 then return ck(t <= 38, "p9 present: box tracks ball, must connect early (t<=38), got t=" .. t)
    else return ck(t >= 41, "p9 absent: floating box connects late (t>=41), got t=" .. t) end
  end }

add{ name = "p10-combo-counter", group = "p10", need = function() return has.p10 end,
  state = "uranus_vs_jupiter.mss", dur = 200,
  frame = function(api)
    local pt = api.pt
    if pt == 5 then
      -- point-blank (probe_p10_vs.lua positions) + reset the P2-defender combo block
      wr(0x1021, 0xE8); wr(0x1022, 0); wr(0x10A1, 0x00); wr(0x10A2, 0x01)
      wr(0x8B0, 0)
    end
    if pt >= 6 then pulse[1] = { down = true } end                      -- crouch dummy
    if pt == 21 or pt == 22 then pulse[0] = { down = true, y = true }   -- 2LP
    elseif pt == 23 then pulse[0] = { down = true }
    elseif pt >= 38 and pt <= 40 then pulse[0] = { down = true, x = true } -- 2HP (chain)
    elseif pt == 41 then pulse[0] = { down = true }
    elseif pt == 42 then pulse[0] = nil end
    -- VRAM oracle on the LEFT counter cells ($10E2/$10E3 = bottom digits)
    local function vw(w) return emu.read(w * 2, emu.memType.snesVideoRam) + 256 * emu.read(w * 2 + 1, emu.memType.snesVideoRam) end
    local drawn = vw(0x10E2) ~= 0x2000 or vw(0x10E3) ~= 0x2000
    if drawn and not api.mem.shownAt then api.mem.shownAt = pt end
    if api.mem.shownAt and not drawn and not api.mem.blankAt then api.mem.blankAt = pt end
    if ram(0x8B0) > (api.mem.maxHits or 0) then api.mem.maxHits = ram(0x8B0) end
  end,
  verdict = function(api)
    local m = api.mem
    if (m.maxHits or 0) < 2 then return ck(false, "chain never reached 2 hits ($08B0 max=" .. tostring(m.maxHits) .. ")") end
    if not m.shownAt then return ck(false, "counter never drawn to VRAM despite " .. m.maxHits .. " hits") end
    if not m.blankAt then return ck(false, "counter drawn @" .. m.shownAt .. " but never cleared (TTL)") end
    return ck(m.blankAt - m.shownAt <= 120, string.format(
      "counter drawn @%d cleared @%d (expect <=120f)", m.shownAt, m.blankAt)) end }

add{ name = "p11-menu-toggle", group = "p11", need = function() return has.p11 end,
  state = "training_p11.mss", dur = 80,
  frame = function(api)
    if api.pt >= 20 and api.pt <= 22 then pulse[0] = { l = true, r = true } elseif api.pt == 23 then pulse[0] = nil end
  end,
  verdict = function() return ck(ram(0x1F005) == 1, "L+R expects MENUOPEN=1, got " .. ram(0x1F005)) end }

add{ name = "p12-taunt-nominal", group = "p12", need = function() return has.p12 end,
  state = "uranus_vs_jupiter.mss", dur = 160,
  frame = function(api)
    if api.pt == 5 then park(1, 120) end
    if api.pt >= 20 and api.pt <= 21 then pulse[0] = { l = true } elseif api.pt == 22 then pulse[0] = nil end
    if api.pt >= 23 then
      local a = ram(0x1001)
      if a == 0x65 or a == 0x66 then api.mem.taunted = true end
      if api.mem.taunted and a == 0x2A then api.mem.tail = true end
    end
  end,
  verdict = function(api) return ck(api.mem.taunted and api.mem.tail, "L expects Uranus misfire act 65/66 then 0x2A tail") end }

add{ name = "p12-taunt-Rheld-excluded", group = "p12", need = function() return has.p12 end,
  state = "uranus_vs_jupiter.mss", dur = 80,
  frame = function(api)
    if api.pt == 5 then park(1, 120) end
    if api.pt >= 20 and api.pt <= 22 then pulse[0] = { l = true, r = true } elseif api.pt == 23 then pulse[0] = nil end
    if api.pt >= 23 then
      local a = ram(0x1001)
      if a == 0x65 or a == 0x66 then api.mem.taunted = true end
    end
  end,
  verdict = function(api) return ck(not api.mem.taunted, "L+R must NOT taunt (p11 menu combo / R exclusion)") end }

add{ name = "p12-taunt-actgate-edge", group = "p12", need = function() return has.p12 end,
  state = "uranus_vs_jupiter.mss", dur = 90,
  frame = function(api)
    if api.pt == 5 then park(1, 120) end
    if api.pt >= 20 and api.pt <= 30 then
      local p = { down = true }
      if api.pt >= 22 and api.pt <= 23 then p.x = true end   -- 2HP
      if api.pt >= 27 and api.pt <= 28 then p.l = true end   -- L during the attack act
      pulse[0] = p
    elseif api.pt == 31 then pulse[0] = nil end
    if api.pt >= 24 then
      local a = ram(0x1001)
      if a == 0x65 or a == 0x66 then api.mem.taunted = true end
    end
  end,
  verdict = function(api) return ck(not api.mem.taunted, "L during 2HP act must not taunt") end }

add{ name = "p13-grant-and-interrupt", group = "p13", need = function() return has.p12 and has.p13 end,
  state = "uranus_vs_jupiter.mss", dur = 400,
  frame = function(api)
    -- phase A (pt 5-200): P2 taunts uninterrupted -> LV2 == 1
    if api.pt == 5 then park(1, 120); wr(0x1F800, 0xA5); wr(0x1F802, 0) end
    if api.pt >= 20 and api.pt <= 21 then pulse[1] = { l = true } elseif api.pt == 22 then pulse[1] = nil end
    if api.pt == 200 then api.mem.lvA = ram(0x1F802) end
    -- phase B (pt 210+): P2 taunts, P1 interrupts with 5HP -> LV stays
    if api.pt == 210 then park(1, 40); wr(0x1F802, 0) end
    if api.pt >= 214 and api.pt <= 215 then pulse[1] = { l = true } elseif api.pt == 216 then pulse[1] = nil end
    if api.pt >= 220 and api.pt <= 221 then pulse[0] = { x = true } elseif api.pt == 222 then pulse[0] = nil end
    if api.pt == 390 then api.mem.lvB = ram(0x1F802) end
  end,
  verdict = function(api)
    return ck(api.mem.lvA == 1 and api.mem.lvB == 0,
      string.format("grant expects LV 1 then interrupt 0, got %s/%s", tostring(api.mem.lvA), tostring(api.mem.lvB)))
  end }

add{ name = "p13-desp-scaled-L3", group = "p13", need = function() return has.p13 end,
  state = "jupiter_vs_venus_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    motion(api, 1, "2141236", "x", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 19, "Jupiter desperation at defender L3 expects 19, got " .. tot)
  end }

add{ name = "p13-throw-exempt-L3", group = "p13", need = function() return has.p13 end,
  state = "neptune_vs_jupiter.mss", dur = 120,
  frame = function(api)
    if api.pt == 5 then park(1, 14); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    if api.pt >= 14 and api.pt <= 17 then
      local p = { x = true }; if onLeft(1) then p.right = true else p.left = true end
      pulse[0] = p
    elseif api.pt == 18 then pulse[0] = nil end
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 20 and grabsum(byk) == 20, "normal throw at L3 must stay 20, got " .. tot)
  end }

add{ name = "p13-uranus-toss-scaled", group = "p13", need = function() return has.p13 end,
  state = "uranus_vs_jupiter.mss", dur = 380,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    motion(api, 1, "632141236", "a", 10, false)
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 34 and grabsum(byk) == 13,
      string.format("Uranus desperation at L3 expects 34 (toss 13), got %d (toss %d)", tot, grabsum(byk)))
  end }

add{ name = "p13-pluto-ticks-scaled", group = "p13", need = function() return has.p13 end,
  state = "pluto_vs_1.mss", dur = 260,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    motion(api, 1, "632146", "x", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 19, "Pluto desperation at defender L3 expects 19, got " .. tot)
  end }

add{ name = "p13-indicator-vs-hidden", group = "p13", need = function() return has.p13 end,
  state = "uranus_vs_jupiter.mss", dur = 60,
  frame = function(api)
    if api.pt == 5 then wr(0x1F800, 0xA5); wr(0x1F801, 3); wr(0x1F802, 2) end
  end,
  verdict = function()
    local function vword(w) return emu.read(w * 2, emu.memType.snesVideoRam) + 256 * emu.read(w * 2 + 1, emu.memType.snesVideoRam) end
    local a, b = vword(0x10E1), vword(0x10FE)
    local drew = (a >= 0x2C50 and a <= 0x2C59) or (b >= 0x2C50 and b <= 0x2C59)
    return ck(not drew, string.format("v3.4: indicator must NOT draw in VS even at levels (cells %04X/%04X)", a, b))
  end }

add{ name = "p14-spd-uranus-scaled", group = "p14", need = function() return has.p13 and has.p14 end,
  state = "uranus_vs_jupiter.mss", dur = 200,
  frame = function(api)
    if api.pt == 5 then park(1, 20); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    motion(api, 1, "6321478", "a", 10, false, 2)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 13, "Uranus SPD at defender L3 expects 13 (Guts Grip), got " .. tot)
  end }

add{ name = "p14-spd-jupiter-scaled", group = "p14", need = function() return has.p13 and has.p14 end,
  state = "jupiter_vs_venus_clean.mss", dur = 220,
  frame = function(api)
    if api.pt == 5 then park(1, 20); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    motion(api, 1, "6321478", "x", 10, false, 2)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 10 and grabwrites() == 5, string.format("Jupiter SPD at L3 expects 5x2=10, got %d (%d writes)", tot, grabwrites()))
  end }

add{ name = "p14-giantswing-lp-scaled", group = "p14", need = function() return has.p13 and has.p14 end,
  state = "jupiter_vs_venus_clean.mss", dur = 220,
  frame = function(api)
    if api.pt == 5 then park(1, 20); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    motion(api, 1, "6248", "y", 10, false, 2)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 8 and grabwrites() == 4, string.format("Giant Swing LP at L3 expects 4x2=8, got %d (%d writes)", tot, grabwrites()))
  end }

-- The two CONFIG-SCREEN patches. Both are menu behaviour, so they run from
-- fixtures taken on that screen with P1's cursor on row 0 (モード):
--   traces/config_vs_clean.mss   2P VS   ($8D=1)
--   traces/config_com_clean.mss  vs COM  ($8D=2)
-- Both were made on the CLEAN ROM by `tools/probe_acs_select.lua SAVE=<name>`
-- and are force-added to git. Two facts the fixtures encode, each of which cost
-- a wrong measurement first: every COLUMN has its own row cursor ($1800 for P1,
-- $1880 for P2 — the mode-row handler firing proves nothing about P1), and the
-- モード row has only TWO values, so an even number of RIGHT presses lands back
-- on マニュアル and reads exactly like an inert row.
local function cfgcell(a) return ram(a) | (ram(a + 1) << 8) end

add{ name = "p15-mode-row-inert", group = "p15", need = function() return true end,  -- dual-mode
  state = "config_vs_clean.mss", dur = 90,
  frame = function(api)
    if api.pt >= 20 and api.pt <= 23 then pulse[0] = { right = true }
    elseif api.pt == 24 then pulse[0] = nil end
  end,
  verdict = function()
    local mode = cfgcell(0x1806)     -- P1's COMMITTED mode: 0 マニュアル, 2 オート
    if has.p15 then
      return ck(mode == 0, "p15 present: one RIGHT on the mode row must not commit "
        .. "a new mode, got $1806=" .. mode)
    end
    return ck(mode == 2, "p15 absent: one RIGHT on the mode row must select オート, "
      .. "got $1806=" .. mode)
  end }

add{ name = "p18-no-acs-in-2p-vs", group = "p18", need = function() return true end,  -- dual-mode
  state = "config_vs_clean.mss", dur = 200,
  frame = function(api)
    if api.pt >= 20 and api.pt <= 26 then pulse[0] = { select = true }
    elseif api.pt == 27 then pulse[0] = nil end
  end,
  verdict = function()
    local st = ram(0x8A)             -- menu state: $05 = ACS, $00 = start the match
    if has.p18 then
      return ck(st == 0x00, "p18 present: SELECT in 2P VS must start the match, "
        .. string.format("got $8A=%02X", st))
    end
    return ck(st == 0x05, "p18 absent: SELECT in 2P VS must open ACS, "
      .. string.format("got $8A=%02X", st))
  end }

-- The control that makes the one above mean something: patch 18 must remove a
-- MODE\'s access, not break SELECT. vs-COM keeps ACS on every build.
add{ name = "p18-acs-kept-in-vs-com", group = "p18", need = function() return true end,
  state = "config_com_clean.mss", dur = 200,
  frame = function(api)
    if api.pt >= 20 and api.pt <= 26 then pulse[0] = { select = true }
    elseif api.pt == 27 then pulse[0] = nil end
  end,
  verdict = function()
    local st = ram(0x8A)
    return ck(st == 0x05, "SELECT in 1P-vs-COM must open ACS on every build, "
      .. string.format("got $8A=%02X", st))
  end }

local function fullmode() return FULL == true end

add{ name = "full-desp-jupiter-crouch62", group = "full", need = fullmode, state = "jupiter_vs_venus_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    motion(api, 1, "2141236", "x", 10, false)
  end,
  verdict = function() local tot = total() return ck(tot == 62, "Jupiter desperation vs crouch expects 62, got " .. tot) end }

add{ name = "full-desp-venus-crouch48", group = "full", need = fullmode, state = "venus_vs_jupiter_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    motion(api, 1, "4123632", "x", 10, false)
  end,
  verdict = function() local tot = total() return ck(tot == 48, "Venus desperation vs crouch expects 48, got " .. tot) end }

add{ name = "full-desp-neptune-crouch37", group = "full", need = fullmode, state = "neptune_vs_jupiter.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 60) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    motion(api, 1, "6236236", "x", 10, true)
  end,
  verdict = function() local tot = total() return ck(tot == 37, "Neptune desperation vs crouch expects 37, got " .. tot) end }

add{ name = "full-desp-moon-crouch48", group = "full", need = fullmode, state = "moon_vs_moon.mss", dur = 160,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 40) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    motion(api, 1, "2363214", "a", 10, true)
  end,
  verdict = function() local tot = total() return ck(tot == 48, "Moon desperation vs crouch expects 48, got " .. tot) end }

add{ name = "full-desp-mars-crouch32", group = "full", need = fullmode, state = "pluto_vs_3.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x10); wr(0x801, 0x10); park(2, 70) end
    if api.pt >= 6 then pulse[0] = { down = true } end
    motion(api, 2, "6321412", "a", 10, false)
  end,
  verdict = function() local tot = total() return ck(tot == 32, "Mars desperation vs crouch expects 32, got " .. tot) end }

add{ name = "full-desp-pluto-crouch49", group = "full", need = fullmode, state = "pluto_vs_1.mss", dur = 260,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    motion(api, 1, "632146", "x", 10, false)
  end,
  verdict = function() local tot = total() return ck(tot == 49, "Pluto desperation vs crouch expects 49, got " .. tot) end }

add{ name = "full-chip-pluto-striketthrow1", group = "full", need = fullmode, state = "pluto_vs_1.mss", dur = 200,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 60) end
    if api.pt >= 6 then
      local p = {}
      if onLeft(1) then p.right = true else p.left = true end
      pulse[1] = p
    end
    motion(api, 1, "632146", "x", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 1 and ram(0x1081) ~= 0x1C, "blocked Dimension Danse expects 1 chip and NO grab, got " .. tot)
  end }

add{ name = "full-chip-moon-zero", group = "full", need = fullmode, state = "moon_vs_moon.mss", dur = 200,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 40) end
    if api.pt >= 6 then
      local p = {}
      if onLeft(1) then p.right = true else p.left = true end
      pulse[1] = p
    end
    motion(api, 1, "2363214", "a", 10, true)
  end,
  verdict = function()
    return ck(#hits == 0, "blocked Silver Crystal Operation expects ZERO chip writes, got " .. #hits)
  end }

add{ name = "full-chip-mars-full32", group = "full", need = fullmode, state = "pluto_vs_3.mss", dur = 200,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x10); wr(0x801, 0x10); park(2, 60) end
    if api.pt >= 6 then
      if onLeft(2) then pulse[0] = { right = true } else pulse[0] = { left = true } end
    end
    motion(api, 2, "6321412", "a", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 32, "blocked Snake Flare expects full 32 chip (4x8), got " .. tot)
  end }

add{ name = "stack-counterhit-x-guts-72to29", group = "stack", need = function() return has.p12 and has.p13 end,
  state = "jupiter_vs_venus_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70); wr(0x1F800, 0xA5); wr(0x1F802, 3) end
    if api.pt >= 45 and api.pt <= 46 then pulse[1] = { l = true } elseif api.pt == 47 then pulse[1] = nil end
    motion(api, 1, "2141236", "x", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 29, "countered desperation (72) at L3 expects 29 (v3.3 wide tables), got " .. tot)
  end }


add{ name = "base-desp-moon-proj48", group = "base", state = "moon_vs_moon.mss", dur = 160,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 40) end
    motion(api, 1, "2363214", "a", 10, true)
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 48 and (byk.PROJ or 0) == 48, string.format("Moon desperation expects PROJ 48, got tot=%d proj=%d", tot, byk.PROJ or 0))
  end }

add{ name = "base-desp-mercury-strike48", group = "base", state = "pluto_vs_2.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x10); wr(0x801, 0x10); park(2, 70) end
    motion(api, 2, "632146", "a", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 48 and #hits == 1, string.format("Mercury desperation expects single 48, got tot=%d n=%d", tot, #hits))
  end }

add{ name = "base-desp-mars-proj32", group = "base", state = "pluto_vs_3.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x10); wr(0x801, 0x10); park(2, 70) end
    motion(api, 2, "6321412", "a", 10, false)
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 32 and (byk.PROJ or 0) == 32, string.format("Mars desperation expects PROJ 32, got tot=%d proj=%d", tot, byk.PROJ or 0))
  end }

add{ name = "base-desp-venus-strike37", group = "base", state = "venus_vs_jupiter_clean.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    motion(api, 1, "4123632", "x", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 37 and #hits == 1, string.format("Venus desperation expects single 37, got tot=%d n=%d", tot, #hits))
  end }

add{ name = "base-desp-chibi-air52", group = "base", state = "pluto_vs_chibi_v07.mss", dur = 220,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x10); wr(0x801, 0x10); park(2, 50) end
    if api.pt >= 10 and api.pt <= 12 then pulse[1] = { up = true } elseif api.pt == 13 then pulse[1] = nil end
    if api.pt >= 22 then motion(api, 2, "63214", "x", 22, false) end
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 52 and (byk.PROJ or 0) == 52, string.format("Chibi air desperation expects PROJ 52, got tot=%d proj=%d", tot, byk.PROJ or 0))
  end }

add{ name = "base-desp-uranus-crouch51", group = "base", state = "uranus_vs_jupiter.mss", dur = 380,
  frame = function(api)
    if api.pt == 5 then wr(0x1049, 0x10); wr(0x800, 0x10); park(1, 70) end
    if api.pt >= 6 then pulse[1] = { down = true } end
    motion(api, 1, "632141236", "a", 10, false)
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 51 and grabsum(byk) == 32,
      string.format("Uranus desperation vs crouch expects 51 (toss 32, fewer rush hits), got %d (toss %d)", tot, grabsum(byk)))
  end }

add{ name = "base-desp-mercury-crouch62", group = "base", state = "pluto_vs_2.mss", dur = 150,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x10); wr(0x801, 0x10); park(2, 70) end
    if api.pt >= 6 then pulse[0] = { down = true } end
    motion(api, 2, "632146", "a", 10, false)
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 62, "Mercury desperation vs crouch expects 62 (crouch column shift), got " .. tot)
  end }

add{ name = "base-desp-chibi-crouch24", group = "base", state = "pluto_vs_chibi_v07.mss", dur = 220,
  frame = function(api)
    if api.pt == 5 then wr(0x10C9, 0x10); wr(0x801, 0x10); park(2, 50) end
    if api.pt >= 6 then pulse[0] = { down = true } end
    if api.pt >= 10 and api.pt <= 12 then pulse[1] = { up = true } elseif api.pt == 13 then pulse[1] = nil end
    if api.pt >= 22 then motion(api, 2, "63214", "x", 22, false) end
  end,
  verdict = function()
    local tot = total()
    return ck(tot == 24, "Chibi air desperation vs crouch expects 24 (hits whiff), got " .. tot)
  end }

add{ name = "base-spd-uranus-toss32", group = "base", state = "uranus_vs_jupiter.mss", dur = 200,
  frame = function(api)
    if api.pt == 5 then park(1, 20) end
    motion(api, 1, "6321478", "a", 10, false, 2)
  end,
  verdict = function()
    local tot, byk = total()
    return ck(tot == 32 and grabsum(byk) == 32 and hits[1] and hits[1].a1 == 0,
      string.format("Uranus SPD expects toss 32 at class 0, got tot=%d toss=%d", tot, grabsum(byk)))
  end }

add{ name = "base-spd-jupiter-carry30", group = "base", state = "jupiter_vs_venus_clean.mss", dur = 220,
  frame = function(api)
    if api.pt == 5 then park(1, 20) end
    motion(api, 1, "6321478", "x", 10, false, 2)
  end,
  verdict = function()
    local tot, byk = total()
    local nticks = grabwrites()
    return ck(tot == 30 and nticks == 5,
      string.format("Jupiter SPD expects 5 carry ticks = 30, got tot=%d ticks=%d", tot, nticks))
  end }

add{ name = "base-throwtech-early-mash", group = "base", state = "venus_vs_jupiter_clean.mss", dur = 120,
  frame = function(api)
    if api.pt == 5 then park(1, 14) end
    if api.pt >= 14 and api.pt <= 17 then
      local p = { x = true }; if onLeft(1) then p.right = true else p.left = true end
      pulse[0] = p
    elseif api.pt == 18 then pulse[0] = nil end
    if not api.mem.grabT and ram(0x1081) == 0x1C then api.mem.grabT = api.pt end
    local g = api.mem.grabT
    if g and api.pt >= g + 4 and api.pt <= g + 14 then
      pulse[1] = (api.pt % 2 == 0) and { y = true } or { b = true, a = true }
    elseif g and api.pt == g + 15 then pulse[1] = nil end
  end,
  verdict = function()
    local ok = #hits == 1 and hits[1].pc % 0x10000 >= 0x850
    return ck(ok, "early mash (grab+4) expects TECH escape, got " .. (#hits > 0 and string.format("pc=%04X", hits[1].pc % 0x10000) or "no writes"))
  end }

add{ name = "p8-tech-window-late-mash", group = "p8", need = function() return true end,  -- dual-mode
  state = "venus_vs_jupiter_clean.mss", dur = 120,
  frame = function(api)
    if api.pt == 5 then park(1, 14) end
    if api.pt >= 14 and api.pt <= 17 then
      local p = { x = true }; if onLeft(1) then p.right = true else p.left = true end
      pulse[0] = p
    elseif api.pt == 18 then pulse[0] = nil end
    if not api.mem.grabT and ram(0x1081) == 0x1C then api.mem.grabT = api.pt end
    local g = api.mem.grabT
    if g and api.pt >= g + 14 and api.pt <= g + 24 then
      pulse[1] = (api.pt % 2 == 0) and { y = true } or { b = true, a = true }
    elseif g and api.pt == g + 25 then pulse[1] = nil end
  end,
  verdict = function()
    if #hits ~= 1 then return ck(false, "expected exactly one throw resolution write, got " .. #hits) end
    local tech = hits[1].pc % 0x10000 >= 0x850
    if has.p8 then return ck(tech, "p8 present: mash at grab+14 must TECH (13f window), got TOSS")
    else return ck(not tech, "p8 absent: mash at grab+14 must be too late (6f-ish window), got TECH") end
  end }

add{ name = "p11-p1hp-low-toggle", group = "p11", need = function() return has.p11 end,
  state = "training_p11.mss", dur = 220,
  frame = function(api)
    if api.pt >= 10 and api.pt <= 12 then pulse[0] = { l = true, r = true } elseif api.pt == 13 then pulse[0] = nil end
    -- cursor starts at row 1: 10 downs at 12f pace (30Hz-safe edges), then right = LOW
    local dn = math.floor((api.pt - 50) / 12)
    if api.pt >= 50 and api.pt < 170 and (api.pt - 50) % 12 < 2 and dn < 10 then pulse[0] = { down = true }
    elseif api.pt >= 50 and api.pt < 170 then pulse[0] = nil end
    if api.pt >= 180 and api.pt <= 181 then pulse[0] = { right = true } elseif api.pt == 182 then pulse[0] = nil end
  end,
  verdict = function()
    return ck(ram(0x1049) == 0x17, string.format("P1 HP LOW expects $1049=0x17, got %02X", ram(0x1049)))
  end }

add{ name = "p13-round-reset-clears-levels", group = "p13", need = function() return has.p13 end,
  state = "uranus_vs_jupiter.mss", dur = 900,
  frame = function(api)
    if api.pt == 5 then
      park(1, 30)
      wr(0x10C9, 0x02); wr(0x801, 0x02)
      wr(0x1F800, 0xA5); wr(0x1F802, 3)
    end
    if api.pt >= 26 and api.pt <= 36 then
      local p = { down = true }; if api.pt >= 30 and api.pt <= 31 then p.x = true end
      pulse[0] = p
    elseif api.pt == 37 then pulse[0] = nil end
    if api.pt > 100 and not api.mem.newRound then
      if ram(0x10C9) == 0x60 and ram(0x1081) == 0 and ram(0x1001) == 0 then
        api.mem.newRound = api.pt
      end
    end
    if api.mem.newRound and api.pt == api.mem.newRound + 60 then
      api.mem.lvAfter = ram(0x1F802)
    end
  end,
  verdict = function(api)
    return ck(api.mem.newRound and api.mem.lvAfter == 0,
      string.format("round reset expects LV cleared, newRound=%s lv=%s", tostring(api.mem.newRound), tostring(api.mem.lvAfter)))
  end }

-- ===== runner =====
local idx, phase, settle = 0, "boot", 0
emu.addEventCallback(function()
  t = t + 1
  if t == 0 then
    -- static layer
    -- Name the ROM in the header: this file is read by tools and by people, and
    -- "which build produced this verdict" was previously answerable only from
    -- memory. emu.getRomInfo() is not available in every headless build, so this
    -- degrades to the plain header rather than failing the run.
    local okri, ri = pcall(emu.getRomInfo)
    log("=== regression run ===" .. ((okri and ri and ri.name) and ("  rom=" .. tostring(ri.name)) or ""))
    for pn, sig in pairs(SIGS) do
      local ok = true
      for _, s in ipairs(sig) do if rom(s[1]) ~= s[2] then ok = false break end end
      has[pn] = ok
    end
    -- issue #29: the p1 stub is shared by both gate variants (0x04 meaty / 0x05 true
    -- combo); detect either and record which, so 1b bundles (REF v.1) read as present
    if has.p1 then
      local g = rom(0x01BE23)
      has.p1 = (g == 0x04 or g == 0x05)
      has.p1gate = has.p1 and g or nil
    end
    local det = {}
    for _, e in ipairs(PATCH_IDS) do det[#det + 1] = e.id .. "=" .. (has[e.id] and "Y" or "-") end
    if has.p1gate then det[1] = det[1] .. string.format("(gate %02X)", has.p1gate) end
    log("detect: " .. table.concat(det, " "))
    -- pre-flight (#4): every savestate the selected tests reference must exist,
    -- reported all at once, before any test runs
    local missing, seen = {}, {}
    for _, tst in ipairs(T) do
      local wanted = (not tst.need or tst.need()) and (not ONLY or tst.name:find(ONLY, 1, true))
      if wanted and tst.state and not seen[tst.state] then
        seen[tst.state] = true
        local f = io.open(TRACE .. tst.state, "rb")
        if f then f:close() else missing[#missing + 1] = tst.state end
      end
    end
    if #missing > 0 then
      log("MISSING FIXTURES (" .. #missing .. "): " .. table.concat(missing, ", "))
      log("aborting — restore them from git (traces/*.mss are force-added) before running")
      emu.stop(1); return
    end
    local nfail = 0
    for r, exp in pairs(MATRIX_ROWS) do
      for c = 0, 15 do
        if rom(0xD081 + r * 16 + c) ~= exp[c + 1] then nfail = nfail + 1 end
      end
    end
    results[#results + 1] = { name = "static-matrix-integrity", ok = nfail == 0, msg = nfail .. " byte mismatches" }
    log(string.format("%s static-matrix-integrity", nfail == 0 and "PASS" or "FAIL"))
    local rfail = 0
    for _, rec in ipairs(DESP_RECORDS) do
      for i = 0, 6 do
        if rom(rec[1] + i) ~= tonumber(rec[2]:sub(i * 2 + 1, i * 2 + 2), 16) then rfail = rfail + 1 end
      end
    end
    results[#results + 1] = { name = "static-desperation-records", ok = rfail == 0, msg = rfail .. " byte mismatches" }
    log(string.format("%s static-desperation-records", rfail == 0 and "PASS" or "FAIL"))
    local hfail = 0
    for i = 0, #MOD_HANDLERS_HEX / 2 - 1 do
      if rom(MOD_HANDLERS_OFF + i) ~= tonumber(MOD_HANDLERS_HEX:sub(i * 2 + 1, i * 2 + 2), 16) then hfail = hfail + 1 end
    end
    results[#results + 1] = { name = "static-modifier-handlers", ok = hfail == 0, msg = hfail .. " byte mismatches" }
    log(string.format("%s static-modifier-handlers", hfail == 0 and "PASS" or "FAIL"))
    -- ⚠ The exp-tier anime line's double-health forces the ACS health stat at
    -- the copy, inside this very span: $C0:87DF `lda $1D0A` (ad 0a 1d) becomes
    -- `lda #imm / nop` (a9 xx ea). That is deliberate, so the check accepts
    -- EITHER form -- but it stays a byte-identity check in both, splicing the
    -- override into the expected image rather than masking the bytes out.
    local expect = CHARLOADER_HEX
    if rom(CHARLOADER_OFF + 15) == 0xA9 and rom(CHARLOADER_OFF + 17) == 0xEA then
      expect = expect:sub(1, 30)
            .. string.format("a9%02xea", rom(CHARLOADER_OFF + 16))
            .. expect:sub(37)
    end
    local cfail = 0
    for i = 0, #expect / 2 - 1 do
      if rom(CHARLOADER_OFF + i) ~= tonumber(expect:sub(i * 2 + 1, i * 2 + 2), 16) then cfail = cfail + 1 end
    end
    results[#results + 1] = { name = "static-charloader-acs", ok = cfail == 0, msg = cfail .. " byte mismatches" }
    log(string.format("%s static-charloader-acs", cfail == 0 and "PASS" or "FAIL"))
    if EXPECT == "clean" then
      local any = false
      for _, e in ipairs(PATCH_IDS) do if has[e.id] then any = true end end
      results[#results + 1] = { name = "static-expect-clean", ok = not any, msg = "patches detected on clean ROM" }
    elseif EXPECT == "all" then
      local all = true
      for _, e in ipairs(PATCH_IDS) do if not has[e.id] then all = false end end
      results[#results + 1] = { name = "static-expect-all", ok = all, msg = "missing patches on all-patches ROM" }
    end
    phase = "next"
  end
  if phase == "next" then
    idx = idx + 1
    while T[idx] and ((T[idx].need and not T[idx].need()) or (ONLY and not T[idx].name:find(ONLY, 1, true))) do
      if not (ONLY and not T[idx].name:find(ONLY, 1, true)) then
        log("SKIP " .. T[idx].name .. " (patch absent)")
      end
      idx = idx + 1
    end
    if not T[idx] then
      local np, nf = 0, 0
      for _, r in ipairs(results) do if r.ok then np = np + 1 else nf = nf + 1; log("  FAILED: " .. r.name .. " — " .. r.msg) end end
      log(nf == 0 and ("ALL PASS (" .. np .. ")") or ("FAILURES (" .. nf .. "/" .. (np + nf) .. ")"))
      emu.stop(nf == 0 and 0 or 1); return
    end
    stateFile = T[idx].state; needLoad = true
    phase = "settle"; settle = 0
    return
  end
  if phase == "settle" then
    settle = settle + 1
    if not needLoad and settle >= 3 then
      phase = "run"; testT0 = t; hits = {}; pulse = {}
      hpSeed = { [0x1049] = ram(0x1049), [0x10C9] = ram(0x10C9) }
      curTest = T[idx]; curTest.mem = {}
    end
    return
  end
  if phase == "run" then
    local api = { pt = t - testT0, mem = curTest.mem }
    curTest.frame(api)
    if api.pt >= curTest.dur then
      local ok, msg = curTest.verdict({ pt = api.pt, mem = curTest.mem })
      results[#results + 1] = { name = curTest.name, ok = ok, msg = msg or "" }
      log(string.format("%s %s%s", ok and "PASS" or "FAIL", curTest.name, ok and "" or (" — " .. (msg or ""))))
      curTest = nil; pulse = {}
      phase = "next"
    end
  end
end, emu.eventType.endFrame)
print("test_regression loaded")
